repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: \.(patch)$

- repo: https://github.com/emzeat/mz-lictools
  rev: v2.7.0
  hooks:
  - id: license-tools

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.6
  hooks:
  - id: clang-format

- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.26.0
  hooks:
  - id: gersemi
    args:
      - -i
      - --indent=2
      - --list-expansion=favour-expansion

- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
