name: CI Testing
on:
  push:
    branches: ["main"]

jobs:
  RunTests:
    runs-on: ubuntu-latest
    container: 7schroet/active-storage-test
    strategy:
      fail-fast: false
      matrix:
        preset: [gcc-debug, gcc-release, clang-debug, clang-release]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: "true"
      - name: Run tests
        run: |
          . /spack/share/spack/setup-env.sh
          spack load mochi-thallium googletest hdf5
          mkdir build && cd $_
          cmake .. --preset ${{ matrix.preset }}
          make -j
          ctest -j

  StaticAnalysis:
    runs-on: ubuntu-latest
    container: 7schroet/active-storage-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: "true"
      - name: Run analysis
        run: |
          . /spack/share/spack/setup-env.sh
          spack load mochi-thallium googletest hdf5
          mkdir build && cd $_
          cmake .. --preset gcc-debug
          make analysis

  Coverage:
    runs-on: ubuntu-latest
    container: 7schroet/active-storage-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: "true"
      - name: Run coverage
        run: |
          . /spack/share/spack/setup-env.sh
          spack load mochi-thallium googletest hdf5
          mkdir build && cd $_
          cmake .. --preset gcc-debug
          make -j
          make coverage |& tee out
          cov=$(grep -o "lines.*:[^%]*" out | grep -o "[0-9]\+[^\.]")
          echo "cov=$cov" >> $GITHUB_ENV
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 8e4e4da82638ecfb5c987b161dc405da
          filename: coverage.svg
          label: "Code Coverage"
          message: "${{ env.cov }}%"
          valColorRange: ${{ env.cov }}
          maxColorRange: 100
          minColorRange: 0
